// Code generated by pigeon; DO NOT EDIT.

// version expression formatter
// will try to translate expressions in a semver version or version range
// compatible one, like this :
// 1.0.rc.1             --> 1.0.0-rc.1
// <0.8                 --> <0.8.0
// ^5 || <=5.0-beta     --> ^5.0.0 || <=5.0.0-beta
package versionformatter

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"io/ioutil"
	"log"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"
)

func Format(expression string) (string, error) {
	got, err := ParseReader("", strings.NewReader(expression))
	if err != nil {
		log.Fatal("👮 In '"+expression+"':\n", err)
		return "", err
	}
	return got.(string), err
}

func toIfaceSlice(v interface{}) []interface{} {
	if v == nil {
		return nil
	}
	return v.([]interface{})
}

var g = &grammar{
	rules: []*rule{
		{
			name: "Input",
			pos:  position{line: 29, col: 1, offset: 656},
			expr: &actionExpr{
				pos: position{line: 29, col: 10, offset: 665},
				run: (*parser).callonInput1,
				expr: &seqExpr{
					pos: position{line: 29, col: 10, offset: 665},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 29, col: 10, offset: 665},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 29, col: 12, offset: 667},
							label: "expr",
							expr: &choiceExpr{
								pos: position{line: 29, col: 18, offset: 673},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 29, col: 18, offset: 673},
										name: "RangeList",
									},
									&ruleRefExpr{
										pos:  position{line: 29, col: 30, offset: 685},
										name: "Query",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 29, col: 37, offset: 692},
							name: "_",
						},
						&ruleRefExpr{
							pos:  position{line: 29, col: 39, offset: 694},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "RangeList",
			pos:  position{line: 34, col: 1, offset: 774},
			expr: &actionExpr{
				pos: position{line: 34, col: 14, offset: 787},
				run: (*parser).callonRangeList1,
				expr: &seqExpr{
					pos: position{line: 34, col: 14, offset: 787},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 34, col: 14, offset: 787},
							label: "head",
							expr: &ruleRefExpr{
								pos:  position{line: 34, col: 19, offset: 792},
								name: "Range",
							},
						},
						&labeledExpr{
							pos:   position{line: 34, col: 25, offset: 798},
							label: "tail",
							expr: &zeroOrMoreExpr{
								pos: position{line: 34, col: 30, offset: 803},
								expr: &ruleRefExpr{
									pos:  position{line: 34, col: 31, offset: 804},
									name: "RangeSubList",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "RangeSubList",
			pos:  position{line: 46, col: 1, offset: 1002},
			expr: &actionExpr{
				pos: position{line: 46, col: 17, offset: 1018},
				run: (*parser).callonRangeSubList1,
				expr: &seqExpr{
					pos: position{line: 46, col: 17, offset: 1018},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 46, col: 17, offset: 1018},
							label: "separator",
							expr: &ruleRefExpr{
								pos:  position{line: 46, col: 27, offset: 1028},
								name: "RangeListSeparator",
							},
						},
						&labeledExpr{
							pos:   position{line: 46, col: 46, offset: 1047},
							label: "version",
							expr: &ruleRefExpr{
								pos:  position{line: 46, col: 54, offset: 1055},
								name: "Version",
							},
						},
					},
				},
			},
		},
		{
			name: "RangeListSeparator",
			pos:  position{line: 50, col: 1, offset: 1120},
			expr: &actionExpr{
				pos: position{line: 50, col: 23, offset: 1142},
				run: (*parser).callonRangeListSeparator1,
				expr: &choiceExpr{
					pos: position{line: 50, col: 24, offset: 1143},
					alternatives: []interface{}{
						&seqExpr{
							pos: position{line: 50, col: 24, offset: 1143},
							exprs: []interface{}{
								&ruleRefExpr{
									pos:  position{line: 50, col: 24, offset: 1143},
									name: "CommaOrPipe",
								},
								&ruleRefExpr{
									pos:  position{line: 50, col: 36, offset: 1155},
									name: "_",
								},
							},
						},
						&seqExpr{
							pos: position{line: 50, col: 40, offset: 1159},
							exprs: []interface{}{
								&ruleRefExpr{
									pos:  position{line: 50, col: 40, offset: 1159},
									name: "MandatoryWhiteSpace",
								},
								&ruleRefExpr{
									pos:  position{line: 50, col: 60, offset: 1179},
									name: "CommaOrPipe",
								},
								&ruleRefExpr{
									pos:  position{line: 50, col: 72, offset: 1191},
									name: "_",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 50, col: 76, offset: 1195},
							name: "MandatoryWhiteSpace",
						},
					},
				},
			},
		},
		{
			name: "Range",
			pos:  position{line: 54, col: 1, offset: 1248},
			expr: &choiceExpr{
				pos: position{line: 54, col: 10, offset: 1257},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 54, col: 10, offset: 1257},
						name: "PrimitiveRange",
					},
					&ruleRefExpr{
						pos:  position{line: 54, col: 27, offset: 1274},
						name: "Version",
					},
					&ruleRefExpr{
						pos:  position{line: 54, col: 37, offset: 1284},
						name: "TildeRange",
					},
					&ruleRefExpr{
						pos:  position{line: 54, col: 50, offset: 1297},
						name: "CaretRange",
					},
				},
			},
		},
		{
			name: "PrimitiveRange",
			pos:  position{line: 56, col: 1, offset: 1309},
			expr: &actionExpr{
				pos: position{line: 56, col: 19, offset: 1327},
				run: (*parser).callonPrimitiveRange1,
				expr: &seqExpr{
					pos: position{line: 56, col: 20, offset: 1328},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 56, col: 20, offset: 1328},
							label: "startop",
							expr: &ruleRefExpr{
								pos:  position{line: 56, col: 28, offset: 1336},
								name: "StartRangeOperator",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 56, col: 47, offset: 1355},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 56, col: 49, offset: 1357},
							label: "start",
							expr: &ruleRefExpr{
								pos:  position{line: 56, col: 55, offset: 1363},
								name: "Version",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 56, col: 63, offset: 1371},
							name: "_",
						},
						&zeroOrOneExpr{
							pos: position{line: 56, col: 65, offset: 1373},
							expr: &ruleRefExpr{
								pos:  position{line: 56, col: 65, offset: 1373},
								name: "CommaOrPipe",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 56, col: 78, offset: 1386},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 56, col: 80, offset: 1388},
							label: "endop",
							expr: &ruleRefExpr{
								pos:  position{line: 56, col: 86, offset: 1394},
								name: "EndRangeOperator",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 56, col: 103, offset: 1411},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 56, col: 105, offset: 1413},
							label: "end",
							expr: &ruleRefExpr{
								pos:  position{line: 56, col: 109, offset: 1417},
								name: "Version",
							},
						},
					},
				},
			},
		},
		{
			name: "StartRangeOperator",
			pos:  position{line: 60, col: 1, offset: 1536},
			expr: &choiceExpr{
				pos: position{line: 60, col: 23, offset: 1558},
				alternatives: []interface{}{
					&litMatcher{
						pos:        position{line: 60, col: 23, offset: 1558},
						val:        ">=",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 60, col: 30, offset: 1565},
						val:        ">",
						ignoreCase: false,
					},
				},
			},
		},
		{
			name: "EndRangeOperator",
			pos:  position{line: 62, col: 1, offset: 1570},
			expr: &choiceExpr{
				pos: position{line: 62, col: 21, offset: 1590},
				alternatives: []interface{}{
					&litMatcher{
						pos:        position{line: 62, col: 21, offset: 1590},
						val:        "<=",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 62, col: 28, offset: 1597},
						val:        "<",
						ignoreCase: false,
					},
				},
			},
		},
		{
			name: "CommaOrPipe",
			pos:  position{line: 64, col: 1, offset: 1602},
			expr: &choiceExpr{
				pos: position{line: 64, col: 16, offset: 1617},
				alternatives: []interface{}{
					&litMatcher{
						pos:        position{line: 64, col: 16, offset: 1617},
						val:        ",",
						ignoreCase: false,
					},
					&actionExpr{
						pos: position{line: 64, col: 22, offset: 1623},
						run: (*parser).callonCommaOrPipe3,
						expr: &litMatcher{
							pos:        position{line: 64, col: 22, offset: 1623},
							val:        "|",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "HyphenRange",
			pos:  position{line: 68, col: 1, offset: 1659},
			expr: &actionExpr{
				pos: position{line: 68, col: 16, offset: 1674},
				run: (*parser).callonHyphenRange1,
				expr: &seqExpr{
					pos: position{line: 68, col: 17, offset: 1675},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 68, col: 17, offset: 1675},
							label: "start",
							expr: &ruleRefExpr{
								pos:  position{line: 68, col: 23, offset: 1681},
								name: "Version",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 68, col: 31, offset: 1689},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 68, col: 33, offset: 1691},
							val:        "-",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 68, col: 37, offset: 1695},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 68, col: 39, offset: 1697},
							label: "end",
							expr: &ruleRefExpr{
								pos:  position{line: 68, col: 43, offset: 1701},
								name: "Version",
							},
						},
					},
				},
			},
		},
		{
			name: "XRange",
			pos:  position{line: 74, col: 1, offset: 1819},
			expr: &actionExpr{
				pos: position{line: 74, col: 11, offset: 1829},
				run: (*parser).callonXRange1,
				expr: &labeledExpr{
					pos:   position{line: 74, col: 11, offset: 1829},
					label: "version",
					expr: &ruleRefExpr{
						pos:  position{line: 74, col: 19, offset: 1837},
						name: "Version",
					},
				},
			},
		},
		{
			name: "TildeRange",
			pos:  position{line: 80, col: 1, offset: 1928},
			expr: &actionExpr{
				pos: position{line: 80, col: 15, offset: 1942},
				run: (*parser).callonTildeRange1,
				expr: &seqExpr{
					pos: position{line: 80, col: 16, offset: 1943},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 80, col: 16, offset: 1943},
							val:        "~",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 80, col: 20, offset: 1947},
							label: "version",
							expr: &ruleRefExpr{
								pos:  position{line: 80, col: 28, offset: 1955},
								name: "Version",
							},
						},
					},
				},
			},
		},
		{
			name: "CaretRange",
			pos:  position{line: 86, col: 1, offset: 2057},
			expr: &actionExpr{
				pos: position{line: 86, col: 15, offset: 2071},
				run: (*parser).callonCaretRange1,
				expr: &seqExpr{
					pos: position{line: 86, col: 16, offset: 2072},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 86, col: 16, offset: 2072},
							val:        "^",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 86, col: 20, offset: 2076},
							label: "version",
							expr: &ruleRefExpr{
								pos:  position{line: 86, col: 28, offset: 2084},
								name: "Version",
							},
						},
					},
				},
			},
		},
		{
			name: "Query",
			pos:  position{line: 92, col: 1, offset: 2186},
			expr: &actionExpr{
				pos: position{line: 92, col: 10, offset: 2195},
				run: (*parser).callonQuery1,
				expr: &seqExpr{
					pos: position{line: 92, col: 10, offset: 2195},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 92, col: 10, offset: 2195},
							label: "head",
							expr: &ruleRefExpr{
								pos:  position{line: 92, col: 15, offset: 2200},
								name: "UnaryAndVersion",
							},
						},
						&labeledExpr{
							pos:   position{line: 92, col: 31, offset: 2216},
							label: "tail",
							expr: &ruleRefExpr{
								pos:  position{line: 92, col: 36, offset: 2221},
								name: "OptionalOperatorExpressions",
							},
						},
					},
				},
			},
		},
		{
			name: "OptionalOperatorExpressions",
			pos:  position{line: 98, col: 1, offset: 2352},
			expr: &actionExpr{
				pos: position{line: 98, col: 32, offset: 2383},
				run: (*parser).callonOptionalOperatorExpressions1,
				expr: &labeledExpr{
					pos:   position{line: 98, col: 32, offset: 2383},
					label: "ops",
					expr: &zeroOrMoreExpr{
						pos: position{line: 98, col: 36, offset: 2387},
						expr: &ruleRefExpr{
							pos:  position{line: 98, col: 37, offset: 2388},
							name: "OperatorExpression",
						},
					},
				},
			},
		},
		{
			name: "OperatorExpression",
			pos:  position{line: 113, col: 1, offset: 2649},
			expr: &actionExpr{
				pos: position{line: 113, col: 23, offset: 2671},
				run: (*parser).callonOperatorExpression1,
				expr: &seqExpr{
					pos: position{line: 113, col: 23, offset: 2671},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 113, col: 23, offset: 2671},
							label: "op",
							expr: &ruleRefExpr{
								pos:  position{line: 113, col: 26, offset: 2674},
								name: "SpacedOperator",
							},
						},
						&labeledExpr{
							pos:   position{line: 113, col: 41, offset: 2689},
							label: "expr",
							expr: &ruleRefExpr{
								pos:  position{line: 113, col: 46, offset: 2694},
								name: "Query",
							},
						},
					},
				},
			},
		},
		{
			name: "SpacedOperator",
			pos:  position{line: 117, col: 1, offset: 2747},
			expr: &actionExpr{
				pos: position{line: 117, col: 19, offset: 2765},
				run: (*parser).callonSpacedOperator1,
				expr: &labeledExpr{
					pos:   position{line: 117, col: 19, offset: 2765},
					label: "op",
					expr: &ruleRefExpr{
						pos:  position{line: 117, col: 22, offset: 2768},
						name: "Operator",
					},
				},
			},
		},
		{
			name: "Primitive",
			pos:  position{line: 127, col: 1, offset: 2918},
			expr: &actionExpr{
				pos: position{line: 127, col: 15, offset: 2932},
				run: (*parser).callonPrimitive1,
				expr: &seqExpr{
					pos: position{line: 127, col: 15, offset: 2932},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 127, col: 15, offset: 2932},
							label: "comparator",
							expr: &ruleRefExpr{
								pos:  position{line: 127, col: 26, offset: 2943},
								name: "Comparator",
							},
						},
						&labeledExpr{
							pos:   position{line: 127, col: 37, offset: 2954},
							label: "partial",
							expr: &ruleRefExpr{
								pos:  position{line: 127, col: 45, offset: 2962},
								name: "Version",
							},
						},
					},
				},
			},
		},
		{
			name: "UnaryAndVersion",
			pos:  position{line: 131, col: 1, offset: 3028},
			expr: &actionExpr{
				pos: position{line: 131, col: 20, offset: 3047},
				run: (*parser).callonUnaryAndVersion1,
				expr: &seqExpr{
					pos: position{line: 131, col: 20, offset: 3047},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 131, col: 20, offset: 3047},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 131, col: 22, offset: 3049},
							label: "unary",
							expr: &ruleRefExpr{
								pos:  position{line: 131, col: 28, offset: 3055},
								name: "OptionalUnary",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 131, col: 42, offset: 3069},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 131, col: 44, offset: 3071},
							label: "version",
							expr: &ruleRefExpr{
								pos:  position{line: 131, col: 52, offset: 3079},
								name: "Version",
							},
						},
					},
				},
			},
		},
		{
			name: "OptionalUnary",
			pos:  position{line: 135, col: 1, offset: 3140},
			expr: &actionExpr{
				pos: position{line: 135, col: 18, offset: 3157},
				run: (*parser).callonOptionalUnary1,
				expr: &labeledExpr{
					pos:   position{line: 135, col: 18, offset: 3157},
					label: "op",
					expr: &zeroOrOneExpr{
						pos: position{line: 135, col: 21, offset: 3160},
						expr: &ruleRefExpr{
							pos:  position{line: 135, col: 21, offset: 3160},
							name: "UnaryOperator",
						},
					},
				},
			},
		},
		{
			name: "Version",
			pos:  position{line: 142, col: 1, offset: 3247},
			expr: &actionExpr{
				pos: position{line: 142, col: 12, offset: 3258},
				run: (*parser).callonVersion1,
				expr: &seqExpr{
					pos: position{line: 142, col: 12, offset: 3258},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 142, col: 12, offset: 3258},
							label: "head",
							expr: &ruleRefExpr{
								pos:  position{line: 142, col: 17, offset: 3263},
								name: "Major",
							},
						},
						&labeledExpr{
							pos:   position{line: 142, col: 23, offset: 3269},
							label: "tail",
							expr: &ruleRefExpr{
								pos:  position{line: 142, col: 28, offset: 3274},
								name: "OptionalMinorPatchPreRelease",
							},
						},
					},
				},
			},
		},
		{
			name: "Major",
			pos:  position{line: 149, col: 1, offset: 3453},
			expr: &ruleRefExpr{
				pos:  position{line: 149, col: 10, offset: 3462},
				name: "VersionPart",
			},
		},
		{
			name: "OptionalMinorPatchPreRelease",
			pos:  position{line: 151, col: 1, offset: 3475},
			expr: &actionExpr{
				pos: position{line: 151, col: 33, offset: 3507},
				run: (*parser).callonOptionalMinorPatchPreRelease1,
				expr: &seqExpr{
					pos: position{line: 151, col: 33, offset: 3507},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 151, col: 33, offset: 3507},
							label: "head",
							expr: &ruleRefExpr{
								pos:  position{line: 151, col: 38, offset: 3512},
								name: "OptionalDotMinor",
							},
						},
						&labeledExpr{
							pos:   position{line: 151, col: 55, offset: 3529},
							label: "tail",
							expr: &ruleRefExpr{
								pos:  position{line: 151, col: 60, offset: 3534},
								name: "OptionalPatchPreRelease",
							},
						},
					},
				},
			},
		},
		{
			name: "OptionalDotMinor",
			pos:  position{line: 155, col: 1, offset: 3607},
			expr: &actionExpr{
				pos: position{line: 155, col: 21, offset: 3627},
				run: (*parser).callonOptionalDotMinor1,
				expr: &labeledExpr{
					pos:   position{line: 155, col: 21, offset: 3627},
					label: "minor",
					expr: &zeroOrOneExpr{
						pos: position{line: 155, col: 27, offset: 3633},
						expr: &ruleRefExpr{
							pos:  position{line: 155, col: 27, offset: 3633},
							name: "DotVersionPart",
						},
					},
				},
			},
		},
		{
			name: "Minor",
			pos:  position{line: 163, col: 1, offset: 3764},
			expr: &ruleRefExpr{
				pos:  position{line: 163, col: 10, offset: 3773},
				name: "VersionPart",
			},
		},
		{
			name: "OptionalPatchPreRelease",
			pos:  position{line: 165, col: 1, offset: 3786},
			expr: &actionExpr{
				pos: position{line: 165, col: 28, offset: 3813},
				run: (*parser).callonOptionalPatchPreRelease1,
				expr: &seqExpr{
					pos: position{line: 165, col: 28, offset: 3813},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 165, col: 28, offset: 3813},
							label: "head",
							expr: &ruleRefExpr{
								pos:  position{line: 165, col: 33, offset: 3818},
								name: "OptionalDotPatch",
							},
						},
						&labeledExpr{
							pos:   position{line: 165, col: 50, offset: 3835},
							label: "tail",
							expr: &ruleRefExpr{
								pos:  position{line: 165, col: 55, offset: 3840},
								name: "OptionalPreRelease",
							},
						},
					},
				},
			},
		},
		{
			name: "OptionalDotPatch",
			pos:  position{line: 174, col: 1, offset: 4004},
			expr: &actionExpr{
				pos: position{line: 174, col: 21, offset: 4024},
				run: (*parser).callonOptionalDotPatch1,
				expr: &labeledExpr{
					pos:   position{line: 174, col: 21, offset: 4024},
					label: "patch",
					expr: &zeroOrOneExpr{
						pos: position{line: 174, col: 27, offset: 4030},
						expr: &ruleRefExpr{
							pos:  position{line: 174, col: 27, offset: 4030},
							name: "DotVersionPart",
						},
					},
				},
			},
		},
		{
			name: "DotVersionPart",
			pos:  position{line: 181, col: 1, offset: 4126},
			expr: &actionExpr{
				pos: position{line: 181, col: 19, offset: 4144},
				run: (*parser).callonDotVersionPart1,
				expr: &seqExpr{
					pos: position{line: 181, col: 19, offset: 4144},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 181, col: 19, offset: 4144},
							name: "Dot",
						},
						&labeledExpr{
							pos:   position{line: 181, col: 23, offset: 4148},
							label: "n",
							expr: &ruleRefExpr{
								pos:  position{line: 181, col: 25, offset: 4150},
								name: "VersionPart",
							},
						},
					},
				},
			},
		},
		{
			name: "Patch",
			pos:  position{line: 188, col: 1, offset: 4240},
			expr: &ruleRefExpr{
				pos:  position{line: 188, col: 10, offset: 4249},
				name: "VersionPart",
			},
		},
		{
			name: "OptionalPreRelease",
			pos:  position{line: 190, col: 1, offset: 4262},
			expr: &actionExpr{
				pos: position{line: 190, col: 23, offset: 4284},
				run: (*parser).callonOptionalPreRelease1,
				expr: &seqExpr{
					pos: position{line: 190, col: 23, offset: 4284},
					exprs: []interface{}{
						&zeroOrOneExpr{
							pos: position{line: 190, col: 23, offset: 4284},
							expr: &choiceExpr{
								pos: position{line: 190, col: 24, offset: 4285},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 190, col: 24, offset: 4285},
										name: "Dash",
									},
									&ruleRefExpr{
										pos:  position{line: 190, col: 29, offset: 4290},
										name: "Dot",
									},
									&ruleRefExpr{
										pos:  position{line: 190, col: 33, offset: 4294},
										name: "Plus",
									},
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 190, col: 40, offset: 4301},
							label: "prerelease",
							expr: &zeroOrOneExpr{
								pos: position{line: 190, col: 51, offset: 4312},
								expr: &ruleRefExpr{
									pos:  position{line: 190, col: 51, offset: 4312},
									name: "PreRelease",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "PreRelease",
			pos:  position{line: 201, col: 1, offset: 4520},
			expr: &actionExpr{
				pos: position{line: 201, col: 15, offset: 4534},
				run: (*parser).callonPreRelease1,
				expr: &zeroOrMoreExpr{
					pos: position{line: 201, col: 15, offset: 4534},
					expr: &ruleRefExpr{
						pos:  position{line: 201, col: 15, offset: 4534},
						name: "PreReleaseContent",
					},
				},
			},
		},
		{
			name: "PreReleaseContent",
			pos:  position{line: 205, col: 1, offset: 4587},
			expr: &choiceExpr{
				pos: position{line: 205, col: 22, offset: 4608},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 205, col: 22, offset: 4608},
						name: "VersionPart",
					},
					&ruleRefExpr{
						pos:  position{line: 205, col: 36, offset: 4622},
						name: "Word",
					},
					&ruleRefExpr{
						pos:  position{line: 205, col: 43, offset: 4629},
						name: "Dot",
					},
					&ruleRefExpr{
						pos:  position{line: 205, col: 49, offset: 4635},
						name: "Dash",
					},
					&ruleRefExpr{
						pos:  position{line: 205, col: 56, offset: 4642},
						name: "Plus",
					},
				},
			},
		},
		{
			name:        "Dot",
			displayName: "\".\"",
			pos:         position{line: 207, col: 1, offset: 4648},
			expr: &actionExpr{
				pos: position{line: 207, col: 12, offset: 4659},
				run: (*parser).callonDot1,
				expr: &charClassMatcher{
					pos:        position{line: 207, col: 12, offset: 4659},
					val:        "[.]",
					chars:      []rune{'.'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
		{
			name:        "Dash",
			displayName: "\"-\"",
			pos:         position{line: 211, col: 1, offset: 4686},
			expr: &actionExpr{
				pos: position{line: 211, col: 13, offset: 4698},
				run: (*parser).callonDash1,
				expr: &charClassMatcher{
					pos:        position{line: 211, col: 13, offset: 4698},
					val:        "[-]",
					chars:      []rune{'-'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
		{
			name:        "Plus",
			displayName: "\"+\"",
			pos:         position{line: 215, col: 1, offset: 4725},
			expr: &actionExpr{
				pos: position{line: 215, col: 13, offset: 4737},
				run: (*parser).callonPlus1,
				expr: &charClassMatcher{
					pos:        position{line: 215, col: 13, offset: 4737},
					val:        "[+]",
					chars:      []rune{'+'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
		{
			name: "Word",
			pos:  position{line: 219, col: 1, offset: 4764},
			expr: &actionExpr{
				pos: position{line: 219, col: 9, offset: 4772},
				run: (*parser).callonWord1,
				expr: &oneOrMoreExpr{
					pos: position{line: 219, col: 9, offset: 4772},
					expr: &charClassMatcher{
						pos:        position{line: 219, col: 9, offset: 4772},
						val:        "[a-zA-Z]",
						ranges:     []rune{'a', 'z', 'A', 'Z'},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
		{
			name: "VersionPart",
			pos:  position{line: 223, col: 1, offset: 4816},
			expr: &choiceExpr{
				pos: position{line: 224, col: 5, offset: 4832},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 224, col: 5, offset: 4832},
						run: (*parser).callonVersionPart2,
						expr: &labeledExpr{
							pos:   position{line: 224, col: 5, offset: 4832},
							label: "wildcard",
							expr: &choiceExpr{
								pos: position{line: 224, col: 15, offset: 4842},
								alternatives: []interface{}{
									&litMatcher{
										pos:        position{line: 224, col: 15, offset: 4842},
										val:        "x",
										ignoreCase: false,
									},
									&litMatcher{
										pos:        position{line: 224, col: 21, offset: 4848},
										val:        "X",
										ignoreCase: false,
									},
									&litMatcher{
										pos:        position{line: 224, col: 27, offset: 4854},
										val:        "*",
										ignoreCase: false,
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 226, col: 7, offset: 4910},
						run: (*parser).callonVersionPart8,
						expr: &labeledExpr{
							pos:   position{line: 226, col: 7, offset: 4910},
							label: "number",
							expr: &ruleRefExpr{
								pos:  position{line: 226, col: 14, offset: 4917},
								name: "Number",
							},
						},
					},
				},
			},
		},
		{
			name: "Number",
			pos:  position{line: 230, col: 1, offset: 4963},
			expr: &actionExpr{
				pos: position{line: 230, col: 11, offset: 4973},
				run: (*parser).callonNumber1,
				expr: &oneOrMoreExpr{
					pos: position{line: 230, col: 11, offset: 4973},
					expr: &charClassMatcher{
						pos:        position{line: 230, col: 11, offset: 4973},
						val:        "[0-9]",
						ranges:     []rune{'0', '9'},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
		{
			name: "Operator",
			pos:  position{line: 241, col: 1, offset: 5231},
			expr: &choiceExpr{
				pos: position{line: 241, col: 13, offset: 5243},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 241, col: 13, offset: 5243},
						name: "Or",
					},
					&ruleRefExpr{
						pos:  position{line: 241, col: 18, offset: 5248},
						name: "MandatoryWhiteSpace",
					},
				},
			},
		},
		{
			name: "Or",
			pos:  position{line: 243, col: 1, offset: 5269},
			expr: &actionExpr{
				pos: position{line: 243, col: 7, offset: 5275},
				run: (*parser).callonOr1,
				expr: &labeledExpr{
					pos:   position{line: 243, col: 7, offset: 5275},
					label: "op",
					expr: &choiceExpr{
						pos: position{line: 243, col: 12, offset: 5280},
						alternatives: []interface{}{
							&seqExpr{
								pos: position{line: 243, col: 12, offset: 5280},
								exprs: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 243, col: 12, offset: 5280},
										name: "MandatoryWhiteSpace",
									},
									&litMatcher{
										pos:        position{line: 243, col: 32, offset: 5300},
										val:        "||",
										ignoreCase: false,
									},
								},
							},
							&litMatcher{
								pos:        position{line: 243, col: 39, offset: 5307},
								val:        "||",
								ignoreCase: false,
							},
						},
					},
				},
			},
		},
		{
			name: "Comparator",
			pos:  position{line: 247, col: 1, offset: 5345},
			expr: &actionExpr{
				pos: position{line: 247, col: 15, offset: 5359},
				run: (*parser).callonComparator1,
				expr: &labeledExpr{
					pos:   position{line: 247, col: 15, offset: 5359},
					label: "op",
					expr: &choiceExpr{
						pos: position{line: 247, col: 19, offset: 5363},
						alternatives: []interface{}{
							&litMatcher{
								pos:        position{line: 247, col: 19, offset: 5363},
								val:        ">=",
								ignoreCase: false,
							},
							&litMatcher{
								pos:        position{line: 247, col: 26, offset: 5370},
								val:        "<=",
								ignoreCase: false,
							},
							&litMatcher{
								pos:        position{line: 247, col: 33, offset: 5377},
								val:        "<",
								ignoreCase: false,
							},
							&litMatcher{
								pos:        position{line: 247, col: 39, offset: 5383},
								val:        ">",
								ignoreCase: false,
							},
							&litMatcher{
								pos:        position{line: 247, col: 45, offset: 5389},
								val:        "=",
								ignoreCase: false,
							},
						},
					},
				},
			},
		},
		{
			name:        "UnaryOperator",
			displayName: "\"unary\"",
			pos:         position{line: 251, col: 1, offset: 5434},
			expr: &actionExpr{
				pos: position{line: 251, col: 26, offset: 5459},
				run: (*parser).callonUnaryOperator1,
				expr: &labeledExpr{
					pos:   position{line: 251, col: 26, offset: 5459},
					label: "op",
					expr: &zeroOrOneExpr{
						pos: position{line: 251, col: 29, offset: 5462},
						expr: &choiceExpr{
							pos: position{line: 251, col: 30, offset: 5463},
							alternatives: []interface{}{
								&litMatcher{
									pos:        position{line: 251, col: 30, offset: 5463},
									val:        "!=",
									ignoreCase: false,
								},
								&litMatcher{
									pos:        position{line: 251, col: 37, offset: 5470},
									val:        "==",
									ignoreCase: false,
								},
								&litMatcher{
									pos:        position{line: 251, col: 43, offset: 5476},
									val:        "<=",
									ignoreCase: false,
								},
								&litMatcher{
									pos:        position{line: 251, col: 50, offset: 5483},
									val:        ">=",
									ignoreCase: false,
								},
								&litMatcher{
									pos:        position{line: 251, col: 57, offset: 5490},
									val:        "<",
									ignoreCase: false,
								},
								&litMatcher{
									pos:        position{line: 251, col: 63, offset: 5496},
									val:        ">",
									ignoreCase: false,
								},
								&litMatcher{
									pos:        position{line: 251, col: 69, offset: 5502},
									val:        "=",
									ignoreCase: false,
								},
								&litMatcher{
									pos:        position{line: 251, col: 75, offset: 5508},
									val:        "!",
									ignoreCase: false,
								},
								&litMatcher{
									pos:        position{line: 251, col: 81, offset: 5514},
									val:        "^",
									ignoreCase: false,
								},
								&litMatcher{
									pos:        position{line: 251, col: 87, offset: 5520},
									val:        "~",
									ignoreCase: false,
								},
								&litMatcher{
									pos:        position{line: 251, col: 93, offset: 5526},
									val:        "",
									ignoreCase: false,
								},
							},
						},
					},
				},
			},
		},
		{
			name:        "MandatoryWhiteSpace",
			displayName: "\"mandatory whitespace\"",
			pos:         position{line: 258, col: 1, offset: 5612},
			expr: &actionExpr{
				pos: position{line: 258, col: 47, offset: 5658},
				run: (*parser).callonMandatoryWhiteSpace1,
				expr: &oneOrMoreExpr{
					pos: position{line: 258, col: 47, offset: 5658},
					expr: &charClassMatcher{
						pos:        position{line: 258, col: 47, offset: 5658},
						val:        "[ \\t\\n\\r]",
						chars:      []rune{' ', '\t', '\n', '\r'},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
		{
			name:        "_",
			displayName: "\"whitespace\"",
			pos:         position{line: 262, col: 1, offset: 5700},
			expr: &zeroOrMoreExpr{
				pos: position{line: 262, col: 19, offset: 5718},
				expr: &charClassMatcher{
					pos:        position{line: 262, col: 19, offset: 5718},
					val:        "[ \\t\\n\\r]",
					chars:      []rune{' ', '\t', '\n', '\r'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
		{
			name: "EOF",
			pos:  position{line: 264, col: 1, offset: 5730},
			expr: &notExpr{
				pos: position{line: 264, col: 8, offset: 5737},
				expr: &anyMatcher{
					line: 264, col: 9, offset: 5738,
				},
			},
		},
	},
}

func (c *current) onInput1(expr interface{}) (interface{}, error) {
	log.Println("👮 Input", expr.(string))
	return expr.(string), nil
}

func (p *parser) callonInput1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInput1(stack["expr"])
}

func (c *current) onRangeList1(head, tail interface{}) (interface{}, error) {
	if tail == nil {
		return head, nil
	}
	tailSl := toIfaceSlice(tail)
	res := head.(string)
	for _, part := range tailSl {
		res += part.(string)
	}
	return res, nil
}

func (p *parser) callonRangeList1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRangeList1(stack["head"], stack["tail"])
}

func (c *current) onRangeSubList1(separator, version interface{}) (interface{}, error) {
	return separator.(string) + version.(string), nil
}

func (p *parser) callonRangeSubList1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRangeSubList1(stack["separator"], stack["version"])
}

func (c *current) onRangeListSeparator1() (interface{}, error) {
	return string(", "), nil
}

func (p *parser) callonRangeListSeparator1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRangeListSeparator1()
}

func (c *current) onPrimitiveRange1(startop, start, endop, end interface{}) (interface{}, error) {
	return string(startop.([]uint8)) + start.(string) + ", " + string(endop.([]uint8)) + end.(string), nil
}

func (p *parser) callonPrimitiveRange1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPrimitiveRange1(stack["startop"], stack["start"], stack["endop"], stack["end"])
}

func (c *current) onCommaOrPipe3() (interface{}, error) {
	return string(", "), nil
}

func (p *parser) callonCommaOrPipe3() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCommaOrPipe3()
}

func (c *current) onHyphenRange1(start, end interface{}) (interface{}, error) {
	var res = start.(string) + " - " + end.(string)
	log.Println("👮 HyphenRange", res)
	return res, nil
}

func (p *parser) callonHyphenRange1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onHyphenRange1(stack["start"], stack["end"])
}

func (c *current) onXRange1(version interface{}) (interface{}, error) {
	var res = version.(string)
	log.Println("👮 XRange", res)
	return res, nil
}

func (p *parser) callonXRange1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onXRange1(stack["version"])
}

func (c *current) onTildeRange1(version interface{}) (interface{}, error) {
	var res = "~" + version.(string)
	log.Println("👮 TildeRange", res)
	return res, nil
}

func (p *parser) callonTildeRange1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTildeRange1(stack["version"])
}

func (c *current) onCaretRange1(version interface{}) (interface{}, error) {
	var res = "^" + version.(string)
	log.Println("👮 CaretRange", res)
	return res, nil
}

func (p *parser) callonCaretRange1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCaretRange1(stack["version"])
}

func (c *current) onQuery1(head, tail interface{}) (interface{}, error) {
	expr := head.(string) + tail.(string)
	log.Println("👮 Expression", expr)
	return expr, nil
}

func (p *parser) callonQuery1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onQuery1(stack["head"], stack["tail"])
}

func (c *current) onOptionalOperatorExpressions1(ops interface{}) (interface{}, error) {
	if ops == nil {
		return "", nil
	}
	opsSl := toIfaceSlice(ops)
	res := ""
	for _, op := range opsSl {
		res += op.(string)
	}
	if res != "" {
		log.Println("👮 OptionalOperatorExpressions", res)
	}
	return res, nil
}

func (p *parser) callonOptionalOperatorExpressions1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOptionalOperatorExpressions1(stack["ops"])
}

func (c *current) onOperatorExpression1(op, expr interface{}) (interface{}, error) {
	return op.(string) + expr.(string), nil
}

func (p *parser) callonOperatorExpression1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOperatorExpression1(stack["op"], stack["expr"])
}

func (c *current) onSpacedOperator1(op interface{}) (interface{}, error) {
	if op == " " {
		return " ", nil
	}
	if op == "," {
		return op.(string) + " ", nil
	}
	return " " + op.(string) + " ", nil
}

func (p *parser) callonSpacedOperator1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSpacedOperator1(stack["op"])
}

func (c *current) onPrimitive1(comparator, partial interface{}) (interface{}, error) {
	return comparator.(string) + partial.(string), nil
}

func (p *parser) callonPrimitive1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPrimitive1(stack["comparator"], stack["partial"])
}

func (c *current) onUnaryAndVersion1(unary, version interface{}) (interface{}, error) {
	return unary.(string) + version.(string), nil
}

func (p *parser) callonUnaryAndVersion1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnaryAndVersion1(stack["unary"], stack["version"])
}

func (c *current) onOptionalUnary1(op interface{}) (interface{}, error) {
	if op == nil {
		return "", nil
	}
	return op.(string), nil
}

func (p *parser) callonOptionalUnary1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOptionalUnary1(stack["op"])
}

func (c *current) onVersion1(head, tail interface{}) (interface{}, error) {
	log.Println("👮 major", head)
	version := head.(string) + tail.(string)
	log.Println("👮 whole version:", version)
	return version, nil
}

func (p *parser) callonVersion1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onVersion1(stack["head"], stack["tail"])
}

func (c *current) onOptionalMinorPatchPreRelease1(head, tail interface{}) (interface{}, error) {
	return head.(string) + tail.(string), nil
}

func (p *parser) callonOptionalMinorPatchPreRelease1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOptionalMinorPatchPreRelease1(stack["head"], stack["tail"])
}

func (c *current) onOptionalDotMinor1(minor interface{}) (interface{}, error) {
	if minor == nil {
		return ".0", nil
	}
	log.Println("👮 minor", minor)
	return minor.(string), nil
}

func (p *parser) callonOptionalDotMinor1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOptionalDotMinor1(stack["minor"])
}

func (c *current) onOptionalPatchPreRelease1(head, tail interface{}) (interface{}, error) {
	if head == nil {
		return ".0" + tail.(string), nil
	}
	log.Println("👮 patch", head)
	return head.(string) + tail.(string), nil

}

func (p *parser) callonOptionalPatchPreRelease1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOptionalPatchPreRelease1(stack["head"], stack["tail"])
}

func (c *current) onOptionalDotPatch1(patch interface{}) (interface{}, error) {
	if patch == nil {
		return ".0", nil
	}
	return patch.(string), nil
}

func (p *parser) callonOptionalDotPatch1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOptionalDotPatch1(stack["patch"])
}

func (c *current) onDotVersionPart1(n interface{}) (interface{}, error) {
	if n == nil {
		return ".0", nil
	}
	return "." + n.(string), nil
}

func (p *parser) callonDotVersionPart1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDotVersionPart1(stack["n"])
}

func (c *current) onOptionalPreRelease1(prerelease interface{}) (interface{}, error) {
	if prerelease == nil {
		return "", nil
	}
	log.Println("👮 prerelease", prerelease)
	if prerelease.(string) == "" {
		return "", nil
	}
	return "-" + prerelease.(string), nil
}

func (p *parser) callonOptionalPreRelease1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOptionalPreRelease1(stack["prerelease"])
}

func (c *current) onPreRelease1() (interface{}, error) {
	return string(c.text), nil
}

func (p *parser) callonPreRelease1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPreRelease1()
}

func (c *current) onDot1() (interface{}, error) {
	return ".", nil
}

func (p *parser) callonDot1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDot1()
}

func (c *current) onDash1() (interface{}, error) {
	return "-", nil
}

func (p *parser) callonDash1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDash1()
}

func (c *current) onPlus1() (interface{}, error) {
	return "=", nil
}

func (p *parser) callonPlus1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPlus1()
}

func (c *current) onWord1() (interface{}, error) {
	return string(c.text), nil
}

func (p *parser) callonWord1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onWord1()
}

func (c *current) onVersionPart2(wildcard interface{}) (interface{}, error) {
	return string(wildcard.([]uint8)), nil

}

func (p *parser) callonVersionPart2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onVersionPart2(stack["wildcard"])
}

func (c *current) onVersionPart8(number interface{}) (interface{}, error) {
	return number.(string), nil

}

func (p *parser) callonVersionPart8() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onVersionPart8(stack["number"])
}

func (c *current) onNumber1() (interface{}, error) {
	var value = string(c.text)
	i, err := strconv.ParseInt(value, 10, 64)
	if err != nil {
		log.Print("Could not translate '", value, "' in 64bit int, will use original value")
		return value, nil
	}

	return strconv.FormatInt(i, 10), nil
}

func (p *parser) callonNumber1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNumber1()
}

func (c *current) onOr1(op interface{}) (interface{}, error) {
	return string("||"), nil
}

func (p *parser) callonOr1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOr1(stack["op"])
}

func (c *current) onComparator1(op interface{}) (interface{}, error) {
	return string(op.([]uint8)), nil
}

func (p *parser) callonComparator1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onComparator1(stack["op"])
}

func (c *current) onUnaryOperator1(op interface{}) (interface{}, error) {
	if op == nil {
		return "", nil
	}
	return string(op.([]uint8)), nil
}

func (p *parser) callonUnaryOperator1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnaryOperator1(stack["op"])
}

func (c *current) onMandatoryWhiteSpace1() (interface{}, error) {
	return string(" "), nil
}

func (p *parser) callonMandatoryWhiteSpace1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMandatoryWhiteSpace1()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expresssions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//     input := "input"
//     stats := Stats{}
//     _, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//     if err != nil {
//         log.Panicln(err)
//     }
//     b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//     if err != nil {
//         log.Panicln(err)
//     }
//     fmt.Println(string(b))
//
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i interface{}, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (interface{}, error) {
	b, err := ioutil.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (interface{}, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return fmt.Sprintf("%d:%d [%d]", p.line, p.col, p.offset)
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]interface{}

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        interface{}
}

type choiceExpr struct {
	pos          position
	alternatives []interface{}
}

type actionExpr struct {
	pos  position
	expr interface{}
	run  func(*parser) (interface{}, error)
}

type recoveryExpr struct {
	pos          position
	expr         interface{}
	recoverExpr  interface{}
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []interface{}
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  interface{}
}

type expr struct {
	pos  position
	expr interface{}
}

type andExpr expr
type notExpr expr
type zeroOrOneExpr expr
type zeroOrMoreExpr expr
type oneOrMoreExpr expr

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
		emptyState: make(storeDict),
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   interface{}
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[interface{}]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]interface{}
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]interface{}

	// emptyState contains an empty storeDict, which is used to optimize cloneState if global "state" store is not used.
	emptyState storeDict
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]interface{})
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr interface{}) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]interface{}, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) in(s string) string {
	p.depth++
	return p.print(strings.Repeat(" ", p.depth)+">", s)
}

func (p *parser) out(s string) string {
	p.depth--
	return p.print(strings.Repeat(" ", p.depth)+"<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() interface{}
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	if len(p.cur.state) == 0 {
		if len(p.emptyState) > 0 {
			p.emptyState = make(storeDict)
		}
		return p.emptyState
	}

	state := make(storeDict, len(p.cur.state))
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node interface{}) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node interface{}, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[interface{}]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[interface{}]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val interface{}, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRule(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return fmt.Sprintf("%s %s %s", strings.Join(list[:len(list)-1], sep), lastSep, list[len(list)-1])
	}
}

func (p *parser) parseRule(rule *rule) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}

	if p.memoize {
		res, ok := p.getMemoized(rule)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
	}

	start := p.pt
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExpr(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}

	if p.memoize {
		p.setMemoized(start, rule, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr interface{}) (interface{}, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val interface{}
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExpr(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExpr(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExpr(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExpr(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	ignoreCase := ""
	if lit.ignoreCase {
		ignoreCase = "i"
	}
	val := fmt.Sprintf("%q%s", lit.val, ignoreCase)
	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, val)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, val)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExpr(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExpr(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRule(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]interface{}, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExpr(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExpr(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExpr(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
