// Code generated by pigeon; DO NOT EDIT.

// yarn.lock parser
package yarnlockparser

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"io/ioutil"
	"log"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"

	"github.com/nearform/gammaray/nodepackage"
)

func ParseYarnLock(expression string, opts ...Option) ([]nodepackage.NodePackage, error) {
	got, err := ParseReader("yarn.lock", strings.NewReader(expression), opts...)
	if err != nil {
		log.Println("👽 In :\n"+expression+"<<EOF>>\n-->", err)
		return nil, err
	}
	return got.([]nodepackage.NodePackage), err
}

func toIfaceSlice(v interface{}) []interface{} {
	if v == nil {
		return nil
	}
	return v.([]interface{})
}

var g = &grammar{
	rules: []*rule{
		{
			name: "Input",
			pos:  position{line: 29, col: 1, offset: 557},
			expr: &actionExpr{
				pos: position{line: 29, col: 9, offset: 565},
				run: (*parser).callonInput1,
				expr: &seqExpr{
					pos: position{line: 29, col: 9, offset: 565},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 29, col: 9, offset: 565},
							name: "Header",
						},
						&labeledExpr{
							pos:   position{line: 29, col: 16, offset: 572},
							label: "deps",
							expr: &ruleRefExpr{
								pos:  position{line: 29, col: 21, offset: 577},
								name: "Body",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 29, col: 26, offset: 582},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "Header",
			pos:  position{line: 33, col: 1, offset: 638},
			expr: &seqExpr{
				pos: position{line: 33, col: 10, offset: 647},
				exprs: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 33, col: 10, offset: 647},
						name: "CommentLine",
					},
					&ruleRefExpr{
						pos:  position{line: 33, col: 22, offset: 659},
						name: "YarnLockfileVersionLine",
					},
				},
			},
		},
		{
			name: "Body",
			pos:  position{line: 35, col: 1, offset: 684},
			expr: &actionExpr{
				pos: position{line: 35, col: 8, offset: 691},
				run: (*parser).callonBody1,
				expr: &seqExpr{
					pos: position{line: 35, col: 8, offset: 691},
					exprs: []interface{}{
						&zeroOrMoreExpr{
							pos: position{line: 35, col: 8, offset: 691},
							expr: &ruleRefExpr{
								pos:  position{line: 35, col: 8, offset: 691},
								name: "LCNM",
							},
						},
						&labeledExpr{
							pos:   position{line: 35, col: 14, offset: 697},
							label: "deps",
							expr: &zeroOrMoreExpr{
								pos: position{line: 35, col: 20, offset: 703},
								expr: &ruleRefExpr{
									pos:  position{line: 35, col: 20, offset: 703},
									name: "Dependency",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Dependency",
			pos:  position{line: 46, col: 1, offset: 957},
			expr: &actionExpr{
				pos: position{line: 46, col: 14, offset: 970},
				run: (*parser).callonDependency1,
				expr: &seqExpr{
					pos: position{line: 46, col: 15, offset: 971},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 46, col: 15, offset: 971},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 46, col: 20, offset: 976},
								name: "DependencyHeaderLine",
							},
						},
						&labeledExpr{
							pos:   position{line: 46, col: 41, offset: 997},
							label: "version",
							expr: &ruleRefExpr{
								pos:  position{line: 46, col: 49, offset: 1005},
								name: "DependencyVersionLine",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 46, col: 71, offset: 1027},
							name: "DependencyResolvedLine",
						},
						&zeroOrOneExpr{
							pos: position{line: 46, col: 94, offset: 1050},
							expr: &seqExpr{
								pos: position{line: 46, col: 95, offset: 1051},
								exprs: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 46, col: 95, offset: 1051},
										name: "DependencyDependenciesHeaderLine",
									},
									&zeroOrMoreExpr{
										pos: position{line: 46, col: 128, offset: 1084},
										expr: &ruleRefExpr{
											pos:  position{line: 46, col: 128, offset: 1084},
											name: "DependencyDependency",
										},
									},
								},
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 46, col: 152, offset: 1108},
							expr: &seqExpr{
								pos: position{line: 46, col: 153, offset: 1109},
								exprs: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 46, col: 153, offset: 1109},
										name: "DependencyOptionalDependenciesHeaderLine",
									},
									&zeroOrMoreExpr{
										pos: position{line: 46, col: 194, offset: 1150},
										expr: &ruleRefExpr{
											pos:  position{line: 46, col: 194, offset: 1150},
											name: "DependencyOptionalDependency",
										},
									},
								},
							},
						},
						&zeroOrMoreExpr{
							pos: position{line: 46, col: 226, offset: 1182},
							expr: &ruleRefExpr{
								pos:  position{line: 46, col: 226, offset: 1182},
								name: "LCNM",
							},
						},
					},
				},
			},
		},
		{
			name: "DependencyHeaderLine",
			pos:  position{line: 52, col: 1, offset: 1352},
			expr: &actionExpr{
				pos: position{line: 52, col: 24, offset: 1375},
				run: (*parser).callonDependencyHeaderLine1,
				expr: &seqExpr{
					pos: position{line: 52, col: 25, offset: 1376},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 52, col: 25, offset: 1376},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 52, col: 30, offset: 1381},
								name: "ListOfPackageQueryExpression",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 52, col: 59, offset: 1410},
							name: "Colon",
						},
						&ruleRefExpr{
							pos:  position{line: 52, col: 65, offset: 1416},
							name: "ROL",
						},
					},
				},
			},
		},
		{
			name: "DependencyVersionLine",
			pos:  position{line: 56, col: 1, offset: 1522},
			expr: &actionExpr{
				pos: position{line: 56, col: 25, offset: 1546},
				run: (*parser).callonDependencyVersionLine1,
				expr: &seqExpr{
					pos: position{line: 56, col: 26, offset: 1547},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 56, col: 26, offset: 1547},
							name: "__",
						},
						&litMatcher{
							pos:        position{line: 56, col: 29, offset: 1550},
							val:        "version",
							ignoreCase: false,
						},
						&oneOrMoreExpr{
							pos: position{line: 56, col: 39, offset: 1560},
							expr: &ruleRefExpr{
								pos:  position{line: 56, col: 39, offset: 1560},
								name: "_",
							},
						},
						&labeledExpr{
							pos:   position{line: 56, col: 42, offset: 1563},
							label: "version",
							expr: &ruleRefExpr{
								pos:  position{line: 56, col: 50, offset: 1571},
								name: "VersionExpression",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 56, col: 68, offset: 1589},
							name: "ROL",
						},
					},
				},
			},
		},
		{
			name: "DependencyResolvedLine",
			pos:  position{line: 60, col: 1, offset: 1702},
			expr: &seqExpr{
				pos: position{line: 60, col: 26, offset: 1727},
				exprs: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 60, col: 26, offset: 1727},
						name: "__",
					},
					&litMatcher{
						pos:        position{line: 60, col: 29, offset: 1730},
						val:        "resolved",
						ignoreCase: false,
					},
					&ruleRefExpr{
						pos:  position{line: 60, col: 40, offset: 1741},
						name: "IgnoredRestOfLine",
					},
				},
			},
		},
		{
			name: "DependencyDependenciesHeaderLine",
			pos:  position{line: 61, col: 1, offset: 1759},
			expr: &seqExpr{
				pos: position{line: 61, col: 36, offset: 1794},
				exprs: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 61, col: 36, offset: 1794},
						name: "__",
					},
					&litMatcher{
						pos:        position{line: 61, col: 39, offset: 1797},
						val:        "dependencies",
						ignoreCase: false,
					},
					&zeroOrMoreExpr{
						pos: position{line: 61, col: 54, offset: 1812},
						expr: &ruleRefExpr{
							pos:  position{line: 61, col: 54, offset: 1812},
							name: "_",
						},
					},
					&ruleRefExpr{
						pos:  position{line: 61, col: 57, offset: 1815},
						name: "Colon",
					},
					&ruleRefExpr{
						pos:  position{line: 61, col: 63, offset: 1821},
						name: "ROL",
					},
				},
			},
		},
		{
			name: "DependencyDependency",
			pos:  position{line: 62, col: 1, offset: 1825},
			expr: &seqExpr{
				pos: position{line: 62, col: 24, offset: 1848},
				exprs: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 62, col: 24, offset: 1848},
						name: "____",
					},
					&ruleRefExpr{
						pos:  position{line: 62, col: 29, offset: 1853},
						name: "PackageNameExpression",
					},
					&oneOrMoreExpr{
						pos: position{line: 62, col: 51, offset: 1875},
						expr: &ruleRefExpr{
							pos:  position{line: 62, col: 51, offset: 1875},
							name: "_",
						},
					},
					&ruleRefExpr{
						pos:  position{line: 62, col: 54, offset: 1878},
						name: "VersionQueryExpression",
					},
					&ruleRefExpr{
						pos:  position{line: 62, col: 77, offset: 1901},
						name: "ROL",
					},
				},
			},
		},
		{
			name: "DependencyOptionalDependenciesHeaderLine",
			pos:  position{line: 63, col: 1, offset: 1905},
			expr: &seqExpr{
				pos: position{line: 63, col: 44, offset: 1948},
				exprs: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 63, col: 44, offset: 1948},
						name: "__",
					},
					&litMatcher{
						pos:        position{line: 63, col: 47, offset: 1951},
						val:        "optionalDependencies",
						ignoreCase: false,
					},
					&zeroOrMoreExpr{
						pos: position{line: 63, col: 70, offset: 1974},
						expr: &ruleRefExpr{
							pos:  position{line: 63, col: 70, offset: 1974},
							name: "_",
						},
					},
					&ruleRefExpr{
						pos:  position{line: 63, col: 73, offset: 1977},
						name: "Colon",
					},
					&ruleRefExpr{
						pos:  position{line: 63, col: 79, offset: 1983},
						name: "ROL",
					},
				},
			},
		},
		{
			name: "DependencyOptionalDependency",
			pos:  position{line: 64, col: 1, offset: 1987},
			expr: &seqExpr{
				pos: position{line: 64, col: 32, offset: 2018},
				exprs: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 64, col: 32, offset: 2018},
						name: "____",
					},
					&ruleRefExpr{
						pos:  position{line: 64, col: 37, offset: 2023},
						name: "PackageNameExpression",
					},
					&oneOrMoreExpr{
						pos: position{line: 64, col: 59, offset: 2045},
						expr: &ruleRefExpr{
							pos:  position{line: 64, col: 59, offset: 2045},
							name: "_",
						},
					},
					&ruleRefExpr{
						pos:  position{line: 64, col: 62, offset: 2048},
						name: "VersionQueryExpression",
					},
					&ruleRefExpr{
						pos:  position{line: 64, col: 85, offset: 2071},
						name: "ROL",
					},
				},
			},
		},
		{
			name: "ListOfPackageQueryExpression",
			pos:  position{line: 66, col: 1, offset: 2076},
			expr: &actionExpr{
				pos: position{line: 66, col: 32, offset: 2107},
				run: (*parser).callonListOfPackageQueryExpression1,
				expr: &seqExpr{
					pos: position{line: 66, col: 32, offset: 2107},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 66, col: 32, offset: 2107},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 66, col: 37, offset: 2112},
								name: "PackageQueryExpression",
							},
						},
						&zeroOrMoreExpr{
							pos: position{line: 66, col: 61, offset: 2136},
							expr: &seqExpr{
								pos: position{line: 66, col: 62, offset: 2137},
								exprs: []interface{}{
									&zeroOrMoreExpr{
										pos: position{line: 66, col: 62, offset: 2137},
										expr: &ruleRefExpr{
											pos:  position{line: 66, col: 62, offset: 2137},
											name: "_",
										},
									},
									&ruleRefExpr{
										pos:  position{line: 66, col: 65, offset: 2140},
										name: "Comma",
									},
									&zeroOrMoreExpr{
										pos: position{line: 66, col: 71, offset: 2146},
										expr: &ruleRefExpr{
											pos:  position{line: 66, col: 71, offset: 2146},
											name: "_",
										},
									},
									&ruleRefExpr{
										pos:  position{line: 66, col: 74, offset: 2149},
										name: "PackageQueryExpression",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "PackageQueryExpression",
			pos:  position{line: 70, col: 1, offset: 2283},
			expr: &choiceExpr{
				pos: position{line: 70, col: 26, offset: 2308},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 70, col: 26, offset: 2308},
						run: (*parser).callonPackageQueryExpression2,
						expr: &seqExpr{
							pos: position{line: 70, col: 27, offset: 2309},
							exprs: []interface{}{
								&ruleRefExpr{
									pos:  position{line: 70, col: 27, offset: 2309},
									name: "Quote",
								},
								&labeledExpr{
									pos:   position{line: 70, col: 33, offset: 2315},
									label: "name",
									expr: &ruleRefExpr{
										pos:  position{line: 70, col: 38, offset: 2320},
										name: "PackageQuery",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 70, col: 51, offset: 2333},
									name: "Quote",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 73, col: 7, offset: 2437},
						run: (*parser).callonPackageQueryExpression8,
						expr: &labeledExpr{
							pos:   position{line: 73, col: 7, offset: 2437},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 73, col: 12, offset: 2442},
								name: "PackageQuery",
							},
						},
					},
				},
			},
		},
		{
			name: "PackageQuery",
			pos:  position{line: 78, col: 1, offset: 2544},
			expr: &actionExpr{
				pos: position{line: 78, col: 16, offset: 2559},
				run: (*parser).callonPackageQuery1,
				expr: &seqExpr{
					pos: position{line: 78, col: 17, offset: 2560},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 78, col: 17, offset: 2560},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 78, col: 22, offset: 2565},
								name: "PackageName",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 78, col: 34, offset: 2577},
							name: "Arobase",
						},
						&ruleRefExpr{
							pos:  position{line: 78, col: 42, offset: 2585},
							name: "VersionQuery",
						},
					},
				},
			},
		},
		{
			name: "PackageNameExpression",
			pos:  position{line: 82, col: 1, offset: 2632},
			expr: &choiceExpr{
				pos: position{line: 82, col: 26, offset: 2657},
				alternatives: []interface{}{
					&seqExpr{
						pos: position{line: 82, col: 26, offset: 2657},
						exprs: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 82, col: 26, offset: 2657},
								name: "Quote",
							},
							&ruleRefExpr{
								pos:  position{line: 82, col: 32, offset: 2663},
								name: "PackageName",
							},
							&ruleRefExpr{
								pos:  position{line: 82, col: 44, offset: 2675},
								name: "Quote",
							},
						},
					},
					&ruleRefExpr{
						pos:  position{line: 82, col: 52, offset: 2683},
						name: "PackageName",
					},
				},
			},
		},
		{
			name: "PackageName",
			pos:  position{line: 83, col: 1, offset: 2696},
			expr: &choiceExpr{
				pos: position{line: 83, col: 15, offset: 2710},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 83, col: 15, offset: 2710},
						run: (*parser).callonPackageName2,
						expr: &seqExpr{
							pos: position{line: 83, col: 16, offset: 2711},
							exprs: []interface{}{
								&ruleRefExpr{
									pos:  position{line: 83, col: 16, offset: 2711},
									name: "Scope",
								},
								&ruleRefExpr{
									pos:  position{line: 83, col: 22, offset: 2717},
									name: "Slash",
								},
								&ruleRefExpr{
									pos:  position{line: 83, col: 28, offset: 2723},
									name: "PackageChars",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 86, col: 7, offset: 2835},
						run: (*parser).callonPackageName7,
						expr: &ruleRefExpr{
							pos:  position{line: 86, col: 7, offset: 2835},
							name: "PackageChars",
						},
					},
				},
			},
		},
		{
			name: "VersionQueryExpression",
			pos:  position{line: 92, col: 1, offset: 2935},
			expr: &choiceExpr{
				pos: position{line: 92, col: 26, offset: 2960},
				alternatives: []interface{}{
					&seqExpr{
						pos: position{line: 92, col: 27, offset: 2961},
						exprs: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 92, col: 27, offset: 2961},
								name: "Quote",
							},
							&ruleRefExpr{
								pos:  position{line: 92, col: 33, offset: 2967},
								name: "VersionQuery",
							},
							&ruleRefExpr{
								pos:  position{line: 92, col: 46, offset: 2980},
								name: "Quote",
							},
						},
					},
					&ruleRefExpr{
						pos:  position{line: 92, col: 55, offset: 2989},
						name: "VersionQuery",
					},
				},
			},
		},
		{
			name:        "VersionExpression",
			displayName: "\"a quoted version number\"",
			pos:         position{line: 93, col: 1, offset: 3002},
			expr: &actionExpr{
				pos: position{line: 93, col: 47, offset: 3048},
				run: (*parser).callonVersionExpression1,
				expr: &seqExpr{
					pos: position{line: 93, col: 48, offset: 3049},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 93, col: 48, offset: 3049},
							name: "Quote",
						},
						&labeledExpr{
							pos:   position{line: 93, col: 54, offset: 3055},
							label: "version",
							expr: &ruleRefExpr{
								pos:  position{line: 93, col: 62, offset: 3063},
								name: "Version",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 93, col: 70, offset: 3071},
							name: "Quote",
						},
					},
				},
			},
		},
		{
			name: "Scope",
			pos:  position{line: 97, col: 1, offset: 3171},
			expr: &seqExpr{
				pos: position{line: 97, col: 9, offset: 3179},
				exprs: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 97, col: 9, offset: 3179},
						name: "Arobase",
					},
					&ruleRefExpr{
						pos:  position{line: 97, col: 17, offset: 3187},
						name: "ScopeChars",
					},
				},
			},
		},
		{
			name:        "LCNM",
			displayName: "\"an empty or commented line\"",
			pos:         position{line: 99, col: 1, offset: 3199},
			expr: &choiceExpr{
				pos: position{line: 99, col: 37, offset: 3235},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 99, col: 37, offset: 3235},
						name: "NewLine",
					},
					&ruleRefExpr{
						pos:  position{line: 99, col: 45, offset: 3243},
						name: "CommentLine",
					},
					&seqExpr{
						pos: position{line: 99, col: 58, offset: 3256},
						exprs: []interface{}{
							&oneOrMoreExpr{
								pos: position{line: 99, col: 58, offset: 3256},
								expr: &ruleRefExpr{
									pos:  position{line: 99, col: 58, offset: 3256},
									name: "_",
								},
							},
							&ruleRefExpr{
								pos:  position{line: 99, col: 61, offset: 3259},
								name: "NewLine",
							},
						},
					},
				},
			},
		},
		{
			name: "ROL",
			pos:  position{line: 101, col: 1, offset: 3269},
			expr: &choiceExpr{
				pos: position{line: 101, col: 7, offset: 3275},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 101, col: 7, offset: 3275},
						name: "CommentLine",
					},
					&ruleRefExpr{
						pos:  position{line: 101, col: 21, offset: 3289},
						name: "EmptyRestOfLine",
					},
				},
			},
		},
		{
			name: "CommentLine",
			pos:  position{line: 102, col: 1, offset: 3305},
			expr: &seqExpr{
				pos: position{line: 102, col: 15, offset: 3319},
				exprs: []interface{}{
					&zeroOrMoreExpr{
						pos: position{line: 102, col: 15, offset: 3319},
						expr: &ruleRefExpr{
							pos:  position{line: 102, col: 15, offset: 3319},
							name: "_",
						},
					},
					&ruleRefExpr{
						pos:  position{line: 102, col: 18, offset: 3322},
						name: "Comment",
					},
					&ruleRefExpr{
						pos:  position{line: 102, col: 26, offset: 3330},
						name: "EOL",
					},
				},
			},
		},
		{
			name: "IgnoredRestOfLine",
			pos:  position{line: 103, col: 1, offset: 3334},
			expr: &seqExpr{
				pos: position{line: 103, col: 21, offset: 3354},
				exprs: []interface{}{
					&zeroOrOneExpr{
						pos: position{line: 103, col: 21, offset: 3354},
						expr: &ruleRefExpr{
							pos:  position{line: 103, col: 21, offset: 3354},
							name: "NotEOL",
						},
					},
					&ruleRefExpr{
						pos:  position{line: 103, col: 29, offset: 3362},
						name: "EOL",
					},
				},
			},
		},
		{
			name: "EmptyRestOfLine",
			pos:  position{line: 104, col: 1, offset: 3366},
			expr: &seqExpr{
				pos: position{line: 104, col: 19, offset: 3384},
				exprs: []interface{}{
					&zeroOrMoreExpr{
						pos: position{line: 104, col: 19, offset: 3384},
						expr: &ruleRefExpr{
							pos:  position{line: 104, col: 19, offset: 3384},
							name: "_",
						},
					},
					&ruleRefExpr{
						pos:  position{line: 104, col: 22, offset: 3387},
						name: "EOL",
					},
				},
			},
		},
		{
			name: "YarnLockfileVersionLine",
			pos:  position{line: 106, col: 1, offset: 3392},
			expr: &seqExpr{
				pos: position{line: 106, col: 27, offset: 3418},
				exprs: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 106, col: 27, offset: 3418},
						name: "Hash",
					},
					&ruleRefExpr{
						pos:  position{line: 106, col: 32, offset: 3423},
						name: "_",
					},
					&litMatcher{
						pos:        position{line: 106, col: 34, offset: 3425},
						val:        "yarn lockfile v1",
						ignoreCase: false,
					},
					&ruleRefExpr{
						pos:  position{line: 106, col: 53, offset: 3444},
						name: "EOL",
					},
				},
			},
		},
		{
			name: "Comment",
			pos:  position{line: 107, col: 1, offset: 3448},
			expr: &seqExpr{
				pos: position{line: 107, col: 11, offset: 3458},
				exprs: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 107, col: 11, offset: 3458},
						name: "Hash",
					},
					&ruleRefExpr{
						pos:  position{line: 107, col: 16, offset: 3463},
						name: "NotEOL",
					},
				},
			},
		},
		{
			name: "PackageChars",
			pos:  position{line: 109, col: 1, offset: 3471},
			expr: &seqExpr{
				pos: position{line: 109, col: 16, offset: 3486},
				exprs: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 109, col: 16, offset: 3486},
						name: "UrlSafeCharNoDotNoUnderscore",
					},
					&zeroOrMoreExpr{
						pos: position{line: 109, col: 45, offset: 3515},
						expr: &ruleRefExpr{
							pos:  position{line: 109, col: 45, offset: 3515},
							name: "UrlSafeChar",
						},
					},
				},
			},
		},
		{
			name: "ScopeChars",
			pos:  position{line: 110, col: 1, offset: 3528},
			expr: &seqExpr{
				pos: position{line: 110, col: 14, offset: 3541},
				exprs: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 110, col: 14, offset: 3541},
						name: "UrlSafeCharNoDotNoUnderscore",
					},
					&zeroOrMoreExpr{
						pos: position{line: 110, col: 43, offset: 3570},
						expr: &ruleRefExpr{
							pos:  position{line: 110, col: 43, offset: 3570},
							name: "UrlSafeChar",
						},
					},
				},
			},
		},
		{
			name:        "VersionQuery",
			displayName: "\"a semver version query\"",
			pos:         position{line: 112, col: 1, offset: 3584},
			expr: &oneOrMoreExpr{
				pos: position{line: 112, col: 41, offset: 3624},
				expr: &choiceExpr{
					pos: position{line: 112, col: 42, offset: 3625},
					alternatives: []interface{}{
						&charClassMatcher{
							pos:        position{line: 112, col: 42, offset: 3625},
							val:        "[0-9^~<>!=xX*. |a-zA-Z]",
							chars:      []rune{'^', '~', '<', '>', '!', '=', 'x', 'X', '*', '.', ' ', '|'},
							ranges:     []rune{'0', '9', 'a', 'z', 'A', 'Z'},
							ignoreCase: false,
							inverted:   false,
						},
						&litMatcher{
							pos:        position{line: 112, col: 66, offset: 3649},
							val:        "-",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name:        "Version",
			displayName: "\"a version number\"",
			pos:         position{line: 113, col: 1, offset: 3655},
			expr: &actionExpr{
				pos: position{line: 113, col: 30, offset: 3684},
				run: (*parser).callonVersion1,
				expr: &oneOrMoreExpr{
					pos: position{line: 113, col: 30, offset: 3684},
					expr: &choiceExpr{
						pos: position{line: 113, col: 31, offset: 3685},
						alternatives: []interface{}{
							&charClassMatcher{
								pos:        position{line: 113, col: 31, offset: 3685},
								val:        "[0-9.+a-zA-Z]",
								chars:      []rune{'.', '+'},
								ranges:     []rune{'0', '9', 'a', 'z', 'A', 'Z'},
								ignoreCase: false,
								inverted:   false,
							},
							&litMatcher{
								pos:        position{line: 113, col: 45, offset: 3699},
								val:        "-",
								ignoreCase: false,
							},
						},
					},
				},
			},
		},
		{
			name: "Alpha",
			pos:  position{line: 118, col: 1, offset: 3785},
			expr: &charClassMatcher{
				pos:        position{line: 118, col: 9, offset: 3793},
				val:        "[a-zA-Z]",
				ranges:     []rune{'a', 'z', 'A', 'Z'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "Digit",
			pos:  position{line: 119, col: 1, offset: 3802},
			expr: &charClassMatcher{
				pos:        position{line: 119, col: 9, offset: 3810},
				val:        "[0-9]",
				ranges:     []rune{'0', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "UrlSafeCharNoDotNoUnderscore",
			pos:  position{line: 121, col: 1, offset: 3817},
			expr: &choiceExpr{
				pos: position{line: 121, col: 32, offset: 3848},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 121, col: 32, offset: 3848},
						name: "Alpha",
					},
					&ruleRefExpr{
						pos:  position{line: 121, col: 40, offset: 3856},
						name: "Digit",
					},
					&litMatcher{
						pos:        position{line: 121, col: 48, offset: 3864},
						val:        "-",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 121, col: 54, offset: 3870},
						val:        "~",
						ignoreCase: false,
					},
				},
			},
		},
		{
			name: "UrlSafeChar",
			pos:  position{line: 122, col: 1, offset: 3874},
			expr: &choiceExpr{
				pos: position{line: 122, col: 15, offset: 3888},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 122, col: 15, offset: 3888},
						name: "Alpha",
					},
					&ruleRefExpr{
						pos:  position{line: 122, col: 23, offset: 3896},
						name: "Digit",
					},
					&litMatcher{
						pos:        position{line: 122, col: 31, offset: 3904},
						val:        "-",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 122, col: 37, offset: 3910},
						val:        ".",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 122, col: 43, offset: 3916},
						val:        "_",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 122, col: 49, offset: 3922},
						val:        "~",
						ignoreCase: false,
					},
				},
			},
		},
		{
			name:        "Hash",
			displayName: "\"a hash\"",
			pos:         position{line: 124, col: 1, offset: 3927},
			expr: &litMatcher{
				pos:        position{line: 124, col: 17, offset: 3943},
				val:        "#",
				ignoreCase: false,
			},
		},
		{
			name:        "Quote",
			displayName: "\"a double quote\"",
			pos:         position{line: 125, col: 1, offset: 3947},
			expr: &litMatcher{
				pos:        position{line: 125, col: 25, offset: 3971},
				val:        "\"",
				ignoreCase: false,
			},
		},
		{
			name:        "Comma",
			displayName: "\"a comma\"",
			pos:         position{line: 126, col: 1, offset: 3976},
			expr: &litMatcher{
				pos:        position{line: 126, col: 19, offset: 3994},
				val:        ",",
				ignoreCase: false,
			},
		},
		{
			name:        "Colon",
			displayName: "\"a colon\"",
			pos:         position{line: 127, col: 1, offset: 3998},
			expr: &litMatcher{
				pos:        position{line: 127, col: 19, offset: 4016},
				val:        ":",
				ignoreCase: false,
			},
		},
		{
			name:        "Arobase",
			displayName: "\"an arobase\"",
			pos:         position{line: 128, col: 1, offset: 4020},
			expr: &litMatcher{
				pos:        position{line: 128, col: 24, offset: 4043},
				val:        "@",
				ignoreCase: false,
			},
		},
		{
			name:        "Slash",
			displayName: "\"a slash\"",
			pos:         position{line: 129, col: 1, offset: 4047},
			expr: &litMatcher{
				pos:        position{line: 129, col: 19, offset: 4065},
				val:        "/",
				ignoreCase: false,
			},
		},
		{
			name:        "NotEOL",
			displayName: "\"any charchter but EOL/EOF\"",
			pos:         position{line: 131, col: 1, offset: 4070},
			expr: &zeroOrMoreExpr{
				pos: position{line: 131, col: 38, offset: 4107},
				expr: &charClassMatcher{
					pos:        position{line: 131, col: 38, offset: 4107},
					val:        "[^\\r\\n]",
					chars:      []rune{'\r', '\n'},
					ignoreCase: false,
					inverted:   true,
				},
			},
		},
		{
			name:        "EOL",
			displayName: "\"End of Line (EOL) or End of File (EOF)\"",
			pos:         position{line: 132, col: 1, offset: 4116},
			expr: &choiceExpr{
				pos: position{line: 132, col: 48, offset: 4163},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 132, col: 48, offset: 4163},
						name: "NewLine",
					},
					&ruleRefExpr{
						pos:  position{line: 132, col: 58, offset: 4173},
						name: "EOF",
					},
				},
			},
		},
		{
			name: "NewLine",
			pos:  position{line: 133, col: 1, offset: 4177},
			expr: &choiceExpr{
				pos: position{line: 133, col: 11, offset: 4187},
				alternatives: []interface{}{
					&litMatcher{
						pos:        position{line: 133, col: 11, offset: 4187},
						val:        "\r\n",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 133, col: 20, offset: 4196},
						val:        "\n",
						ignoreCase: false,
					},
				},
			},
		},
		{
			name:        "____",
			displayName: "\"double indent\"",
			pos:         position{line: 135, col: 1, offset: 4202},
			expr: &seqExpr{
				pos: position{line: 135, col: 24, offset: 4225},
				exprs: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 135, col: 24, offset: 4225},
						name: "__",
					},
					&ruleRefExpr{
						pos:  position{line: 135, col: 27, offset: 4228},
						name: "__",
					},
				},
			},
		},
		{
			name:        "__",
			displayName: "\"single indent\"",
			pos:         position{line: 136, col: 1, offset: 4231},
			expr: &seqExpr{
				pos: position{line: 136, col: 22, offset: 4252},
				exprs: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 136, col: 22, offset: 4252},
						name: "indent",
					},
					&ruleRefExpr{
						pos:  position{line: 136, col: 29, offset: 4259},
						name: "indent",
					},
				},
			},
		},
		{
			name: "indent",
			pos:  position{line: 138, col: 1, offset: 4267},
			expr: &charClassMatcher{
				pos:        position{line: 138, col: 10, offset: 4276},
				val:        "[ \\t]",
				chars:      []rune{' ', '\t'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name:        "_",
			displayName: "\"a whitespace\"",
			pos:         position{line: 140, col: 1, offset: 4283},
			expr: &charClassMatcher{
				pos:        position{line: 140, col: 20, offset: 4302},
				val:        "[ \\t]",
				chars:      []rune{' ', '\t'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "EOF",
			pos:  position{line: 142, col: 1, offset: 4309},
			expr: &notExpr{
				pos: position{line: 142, col: 7, offset: 4315},
				expr: &anyMatcher{
					line: 142, col: 8, offset: 4316,
				},
			},
		},
	},
}

func (c *current) onInput1(deps interface{}) (interface{}, error) {
	return deps.([]nodepackage.NodePackage), nil
}

func (p *parser) callonInput1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInput1(stack["deps"])
}

func (c *current) onBody1(deps interface{}) (interface{}, error) {
	log.Println("👽 Body", deps)

	depsSl := toIfaceSlice(deps)
	var castedDeps []nodepackage.NodePackage
	for _, dep := range depsSl {
		castedDeps = append(castedDeps, dep.(nodepackage.NodePackage))
	}
	return castedDeps, nil
}

func (p *parser) callonBody1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBody1(stack["deps"])
}

func (c *current) onDependency1(name, version interface{}) (interface{}, error) {
	dep := nodepackage.NodePackage{Name: name.(string), Version: version.(string)}
	log.Println("👽 Package of DependencyHeaderLine", dep)
	return dep, nil
}

func (p *parser) callonDependency1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDependency1(stack["name"], stack["version"])
}

func (c *current) onDependencyHeaderLine1(name interface{}) (interface{}, error) {
	log.Println("👽 Package of DependencyHeaderLine", name.(string))
	return name.(string), nil
}

func (p *parser) callonDependencyHeaderLine1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDependencyHeaderLine1(stack["name"])
}

func (c *current) onDependencyVersionLine1(version interface{}) (interface{}, error) {
	log.Println("👽 Package of DependencyVersionLine", version.(string))
	return version.(string), nil
}

func (p *parser) callonDependencyVersionLine1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDependencyVersionLine1(stack["version"])
}

func (c *current) onListOfPackageQueryExpression1(name interface{}) (interface{}, error) {
	log.Println("👽 Package of ListOfPackageQueryExpression", name.(string))
	return name.(string), nil
}

func (p *parser) callonListOfPackageQueryExpression1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onListOfPackageQueryExpression1(stack["name"])
}

func (c *current) onPackageQueryExpression2(name interface{}) (interface{}, error) {
	log.Println("👽 Quoted PackageQuery", name.(string))
	return name.(string), nil

}

func (p *parser) callonPackageQueryExpression2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPackageQueryExpression2(stack["name"])
}

func (c *current) onPackageQueryExpression8(name interface{}) (interface{}, error) {
	log.Println("👽 PackageQuery", name.(string))
	return name.(string), nil

}

func (p *parser) callonPackageQueryExpression8() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPackageQueryExpression8(stack["name"])
}

func (c *current) onPackageQuery1(name interface{}) (interface{}, error) {
	return name.(string), nil
}

func (p *parser) callonPackageQuery1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPackageQuery1(stack["name"])
}

func (c *current) onPackageName2() (interface{}, error) {
	log.Println("👽 Package with Scope", string(c.text))
	return string(c.text), nil

}

func (p *parser) callonPackageName2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPackageName2()
}

func (c *current) onPackageName7() (interface{}, error) {
	log.Println("👽 Package", string(c.text))
	return string(c.text), nil

}

func (p *parser) callonPackageName7() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPackageName7()
}

func (c *current) onVersionExpression1(version interface{}) (interface{}, error) {
	log.Println("👽 VersionExpression", version.(string))
	return version.(string), nil
}

func (p *parser) callonVersionExpression1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onVersionExpression1(stack["version"])
}

func (c *current) onVersion1() (interface{}, error) {
	log.Println("👽 Version", string(c.text))
	return string(c.text), nil
}

func (p *parser) callonVersion1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onVersion1()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expresssions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//     input := "input"
//     stats := Stats{}
//     _, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//     if err != nil {
//         log.Panicln(err)
//     }
//     b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//     if err != nil {
//         log.Panicln(err)
//     }
//     fmt.Println(string(b))
//
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i interface{}, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (interface{}, error) {
	b, err := ioutil.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (interface{}, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return fmt.Sprintf("%d:%d [%d]", p.line, p.col, p.offset)
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]interface{}

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        interface{}
}

type choiceExpr struct {
	pos          position
	alternatives []interface{}
}

type actionExpr struct {
	pos  position
	expr interface{}
	run  func(*parser) (interface{}, error)
}

type recoveryExpr struct {
	pos          position
	expr         interface{}
	recoverExpr  interface{}
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []interface{}
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  interface{}
}

type expr struct {
	pos  position
	expr interface{}
}

type andExpr expr
type notExpr expr
type zeroOrOneExpr expr
type zeroOrMoreExpr expr
type oneOrMoreExpr expr

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
		emptyState: make(storeDict),
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   interface{}
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[interface{}]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]interface{}
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]interface{}

	// emptyState contains an empty storeDict, which is used to optimize cloneState if global "state" store is not used.
	emptyState storeDict
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]interface{})
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr interface{}) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]interface{}, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) in(s string) string {
	p.depth++
	return p.print(strings.Repeat(" ", p.depth)+">", s)
}

func (p *parser) out(s string) string {
	p.depth--
	return p.print(strings.Repeat(" ", p.depth)+"<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() interface{}
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	if len(p.cur.state) == 0 {
		if len(p.emptyState) > 0 {
			p.emptyState = make(storeDict)
		}
		return p.emptyState
	}

	state := make(storeDict, len(p.cur.state))
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node interface{}) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node interface{}, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[interface{}]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[interface{}]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val interface{}, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRule(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return fmt.Sprintf("%s %s %s", strings.Join(list[:len(list)-1], sep), lastSep, list[len(list)-1])
	}
}

func (p *parser) parseRule(rule *rule) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}

	if p.memoize {
		res, ok := p.getMemoized(rule)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
	}

	start := p.pt
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExpr(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}

	if p.memoize {
		p.setMemoized(start, rule, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr interface{}) (interface{}, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val interface{}
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExpr(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExpr(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExpr(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExpr(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	ignoreCase := ""
	if lit.ignoreCase {
		ignoreCase = "i"
	}
	val := fmt.Sprintf("%q%s", lit.val, ignoreCase)
	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, val)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, val)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExpr(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExpr(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRule(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]interface{}, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExpr(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExpr(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExpr(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
